---
title: Coronavirus in the UK
author: Emily Sheehan
date: '2020-09-12'
slug: coronavirus-in-the-uk
categories: []
tags: []
subtitle: "How the shift in public policy??? impacted the incidence of COVID-19 in the United Kingdom" 
summary: "How the shift in public policy??? impacted the incidence of COVID-19 in the United Kingdom"
authors: []
lastmod: '2020-09-12T13:29:35+10:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

```{r load-libraries, include = FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE)
library(tidyverse)
library(coronavirus)
library(naniar)
library(dygraphs)
library(xts) 
library(htmlwidgets)
```

```{r load-data}
data("coronavirus")
update_dataset()
```


```{r filter-uk}
uk <- coronavirus %>%
  filter(country == "United Kingdom")#,
         #type != "recovered") 
```

```{r find-missing-data, include=FALSE}
# Analyse how many variables are missing
naniar::vis_miss(uk, warn_large_data = FALSE)
```

```{r uk-confirmed}
uk_confirmed <- uk %>% 
  filter(type == "confirmed") %>% 
  group_by(date) %>%
  summarise(cases = sum(cases))
```

```{r uk-death}
uk_death <- uk %>% 
  filter(type == "death") %>% 
  group_by(date) %>%
  summarise(cases = sum(cases))
```

Is x axis label necessary? 

```{r confirmed-plot}
#https://www.r-graph-gallery.com/318-custom-dygraphs-time-series-example.html
# create xts to use dygraph
uk_confirmed_dat <- xts(x = uk_confirmed$cases, 
                        order.by = uk_confirmed$date)

# create plot
uk_confirmed_plot <- dygraph(uk_confirmed_dat,
                             main = "Number of New COVID-19 Cases in the United Kingdom per day") %>%
  dyOptions(labelsUTC = TRUE, 
            # fill the graph
            fillGraph=TRUE, 
            # change shade
            fillAlpha=0.2,
            # do not include a grid
            drawGrid = FALSE, 
            colors="red") %>%
  # change the color to midnigth blue
  dyRangeSelector(fillColor = "midnightblue",
                  strokeColor = "midnightblue") %>%
  # change so it draws a line through both the date and the case number
  dyCrosshair(direction = "both") %>%
  dyHighlight(highlightCircleSize = 6, 
              highlightSeriesBackgroundAlpha = 0.2, 
              hideOnMouseOut = FALSE)  %>%
  dyRoller(rollPeriod = 1) %>%
  dyAxis("y", label = "Number of Cases") %>%
  dyAxis("x", label = "Date") %>%
  dySeries("V1", label = "Number of New Daily Cases") 

#saveWidget(uk_confirmed_plot, file=(here::here("content/post/UK/uk_confirmed.html")
widgetframe::frameWidget(uk_confirmed_plot)
```

```{r death-plot}
uk_death_dat <- xts(x = uk_death$cases, 
                        order.by = uk_death$date)

# create plot
uk_death_plot <- dygraph(uk_death_dat,
                             main = "Number of COVID-19 Deaths in the United Kingdom per day") %>%
  dyOptions(labelsUTC = TRUE, 
            # fill the graph
            fillGraph=TRUE, 
            # change shade
            fillAlpha=0.2,
            # do not include a grid
            drawGrid = FALSE, 
            colors="grey") %>%
  # change the color to midnight blue
  dyRangeSelector(fillColor = "midnightblue",
                  strokeColor = "midnightblue") %>%
  # change so it draws a line through both the date and the case number
  dyCrosshair(direction = "both") %>%
  dyHighlight(highlightCircleSize = 6, 
              highlightSeriesBackgroundAlpha = 0.2, 
              hideOnMouseOut = FALSE)  %>%
  dyRoller(rollPeriod = 1) %>%
  dyAxis("y", label = "Number of Deaths per Day") %>%
  dyAxis("x", label = "Date") %>%
  dySeries("V1", label = "Number of Daily Deaths") 

#saveWidget(uk_confirmed_plot, file=(here::here("content/post/UK/uk_confirmed.html")
widgetframe::frameWidget(uk_death_plot)
```


```{r}
uk_confirmed %>%
  ggplot(aes(x = date,
         y = cases)) +
  geom_line()
```

```{r}
ggplot(uk,
       aes(fill = type,
           x = date,
           y = cases)) +
  geom_bar(position = "stack",
           stat = "identity")
```

